//------------------------------------------------------------------------------
// <auto-generated>
//    MES团队制作，不得以任何原因手动变更当前文档
// </auto-generated>
//------------------------------------------------------------------------------

namespace I.MES.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public class MFG_WorkSchedule
    {
        public int ID { get; set; }
        public string FactoryCode { get; set; }
        public System.DateTime ProdDate { get; set; }
        public string PartNo { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string Unit { get; set; }
        public Nullable<int> IsDel { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string WorkVer { get; set; }
    
    
       public object __InheritFrom
       {
           set
           {
               this.CopyFrom(value);
           }
       }
    }

}
