//------------------------------------------------------------------------------
// <auto-generated>
//    MES团队制作，不得以任何原因手动变更当前文档
// </auto-generated>
//------------------------------------------------------------------------------

namespace I.MES.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public class MFG_Part
    {
        public int ID { get; set; }
        public string PartNo { get; set; }
        public string ProjectName { get; set; }
        public string BriefDesc { get; set; }
        public string CompPartNo { get; set; }
        public string MeterialDescrition { get; set; }
        public string PartDescription { get; set; }
        public string VehicleMode { get; set; }
        public string ColorCode { get; set; }
        public string PartLevel { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateMachine { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string ModifyMachine { get; set; }
    
    
       public object __InheritFrom
       {
           set
           {
               this.CopyFrom(value);
           }
       }
    }

}
