//------------------------------------------------------------------------------
// <auto-generated>
//    MES团队制作，不得以任何原因手动变更当前文档
// </auto-generated>
//------------------------------------------------------------------------------

namespace I.MES.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public class MFG_BOM
    {
        public int ID { get; set; }
        public string FactoryCode { get; set; }
        public string ParentPartNo { get; set; }
        public string BomVer { get; set; }
        public int ItemNo { get; set; }
        public string ComponentPartNo { get; set; }
        public decimal Qty { get; set; }
        public System.DateTime EffStartTime { get; set; }
        public System.DateTime EffExpireTime { get; set; }
        public string Type { get; set; }
        public string OperateProcess { get; set; }
        public Nullable<float> Scrp { get; set; }
        public string Ref1 { get; set; }
        public string ProjectType { get; set; }
        public int IsDel { get; set; }
    
    
       public object __InheritFrom
       {
           set
           {
               this.CopyFrom(value);
           }
       }
    }

}
