//------------------------------------------------------------------------------
// <auto-generated>
//    MES团队制作，不得以任何原因手动变更当前文档
// </auto-generated>
//------------------------------------------------------------------------------

namespace I.MES.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public class MFG_ScanPlugin
    {
        public int ID { get; set; }
        public string PluginID { get; set; }
        public string PluginName { get; set; }
        public string PluginType { get; set; }
        public string PluginDesc { get; set; }
        public Nullable<int> IsSelf { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateMachine { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string ModifyMachine { get; set; }
    
    
       public object __InheritFrom
       {
           set
           {
               this.CopyFrom(value);
           }
       }
    }

}
