//------------------------------------------------------------------------------
// <auto-generated>
//    MES团队制作，不得以任何原因手动变更当前文档
// </auto-generated>
//------------------------------------------------------------------------------

namespace I.MES.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public class MFG_PartDetail
    {
        public int ID { get; set; }
        public string FactoryCode { get; set; }
        public string PartNo { get; set; }
        public string PartType { get; set; }
        public string PartDesc { get; set; }
        public string PartDescEn { get; set; }
        public string Unit { get; set; }
        public string MaterialCtgy { get; set; }
        public string BaseMaterial { get; set; }
        public string ProductLevel { get; set; }
        public string ShareProperty { get; set; }
        public string Brand { get; set; }
        public string Critical { get; set; }
        public string Consumable { get; set; }
        public string ProduceLine { get; set; }
        public string PMCode { get; set; }
        public string SpecialPMCode { get; set; }
        public string ExtPurLoc { get; set; }
        public bool NeedIQC { get; set; }
        public string Status { get; set; }
        public string Location { get; set; }
        public string ERPSys { get; set; }
        public bool IsD { get; set; }
        public decimal QtyPerPkg { get; set; }
        public bool IsDel { get; set; }
        public string SizeDimension { get; set; }
        public Nullable<decimal> ReorderPoint { get; set; }
        public string JointlyPartFlag { get; set; }
    
    
       public object __InheritFrom
       {
           set
           {
               this.CopyFrom(value);
           }
       }
    }

}
