//------------------------------------------------------------------------------
// <auto-generated>
//    MES团队制作，不得以任何原因手动变更当前文档
// </auto-generated>
//------------------------------------------------------------------------------

namespace I.MES.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public class MFG_BarcodeBindDet
    {
        public int ID { get; set; }
        public string BindType { get; set; }
        public string MainBarcode { get; set; }
        public string Barcode { get; set; }
        public string BindCfgName { get; set; }
        public Nullable<int> BindStatus { get; set; }
        public string BindUser { get; set; }
        public Nullable<System.DateTime> BindTime { get; set; }
        public string UnbindUser { get; set; }
        public Nullable<System.DateTime> UnbindTime { get; set; }
        public string BindScanSite { get; set; }
    
    
       public object __InheritFrom
       {
           set
           {
               this.CopyFrom(value);
           }
       }
    }

}
