//------------------------------------------------------------------------------
// <auto-generated>
//    MES团队制作，不得以任何原因手动变更当前文档
// </auto-generated>
//------------------------------------------------------------------------------

namespace I.MES.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public class PP_ThightRecord
    {
        public long ID { get; set; }
        public string SerialNum { get; set; }
        public string PartNo { get; set; }
        public string ItemName { get; set; }
        public string StationCode { get; set; }
        public Nullable<int> ScrewNo { get; set; }
        public string Trque { get; set; }
        public string Angel { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> ThightTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateMachine { get; set; }
    
    
       public object __InheritFrom
       {
           set
           {
               this.CopyFrom(value);
           }
       }
    }

}
