//------------------------------------------------------------------------------
// <auto-generated>
//    MES团队制作，不得以任何原因手动变更当前文档
// </auto-generated>
//------------------------------------------------------------------------------

namespace I.MES.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public class SYS_RPTMenu
    {
        public int ID { get; set; }
        public string MenuID { get; set; }
        public string ProgCode { get; set; }
        public string RightID { get; set; }
        public string Url { get; set; }
        public string Target { get; set; }
        public string MenuName { get; set; }
        public string ParentID { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public string IconUrl { get; set; }
        public Nullable<int> IconRow { get; set; }
        public Nullable<int> IconCol { get; set; }
        public string PrivID { get; set; }
    
    
       public object __InheritFrom
       {
           set
           {
               this.CopyFrom(value);
           }
       }
    }

}
