//------------------------------------------------------------------------------
// <auto-generated>
//    MES团队制作，不得以任何原因手动变更当前文档
// </auto-generated>
//------------------------------------------------------------------------------

namespace I.MES.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public class SYS_User
    {
        public int ID { get; set; }
        public string UserAccount { get; set; }
        public string UserName { get; set; }
        public string UserWorkID { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> LatestLoginTime { get; set; }
        public string LatestLoginMachine { get; set; }
        public string LatestModifyUser { get; set; }
        public Nullable<System.DateTime> LatestModifyTime { get; set; }
        public string LatestModifyMachine { get; set; }
        public string CreateUserAccount { get; set; }
        public string CreateMachine { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string DomainAccount { get; set; }
    
    
       public object __InheritFrom
       {
           set
           {
               this.CopyFrom(value);
           }
       }
    }

}
