//------------------------------------------------------------------------------
// <auto-generated>
//    MES团队制作，不得以任何原因手动变更当前文档
// </auto-generated>
//------------------------------------------------------------------------------

namespace I.MES.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public class V_WorkStepParam
    {
        public string StepID { get; set; }
        public string Default_image_address { get; set; }
        public string PartName { get; set; }
        public string Check_key { get; set; }
        public string Screw_the_number { get; set; }
        public string Screw_position { get; set; }
        public string torque { get; set; }
        public string torqueoffset { get; set; }
        public string Screw_picture_Pset { get; set; }
        public string Countdown_time { get; set; }
        public string printparam { get; set; }
        public string picparam { get; set; }
        public string checkparam { get; set; }
        public string inspectionparam { get; set; }
        public string presenceparam { get; set; }
    
    
       public object __InheritFrom
       {
           set
           {
               this.CopyFrom(value);
           }
       }
    }

}
