TRUNCATE TABLE IMES3UAT.dbo.EMS_Alarm
TRUNCATE TABLE IMES3UAT.dbo.EMS_EMWorkOrder
TRUNCATE TABLE IMES3UAT.dbo.EMS_EMWorkOrderLog
TRUNCATE TABLE IMES3UAT.dbo.EMS_IPQCOrder
TRUNCATE TABLE IMES3UAT.dbo.EMS_IPQCOrderLog
TRUNCATE TABLE IMES3UAT.dbo.EMS_NoticeOrder
TRUNCATE TABLE IMES3UAT.dbo.EMS_NoticeOrderDet
TRUNCATE TABLE IMES3UAT.dbo.EMS_PDMWorkOrder
TRUNCATE TABLE IMES3UAT.dbo.EMS_PDMWorkOrderLog
TRUNCATE TABLE IMES3UAT.dbo.EMS_WorkOrderImage
TRUNCATE TABLE IMES3UAT.dbo.EMS_WorkOrderMaintain
TRUNCATE TABLE IMES3UAT.dbo.EMS_WorkOrderPart
TRUNCATE TABLE IMES3UAT.dbo.IFS_HUPkgDetReceiverPending
TRUNCATE TABLE IMES3UAT.dbo.IFS_HUPkgDetSenderPending
TRUNCATE TABLE IMES3UAT.dbo.IFS_HUPkgMstrReceiverPending
TRUNCATE TABLE IMES3UAT.dbo.IFS_HUPkgMstrSenderPending
TRUNCATE TABLE IMES3UAT.dbo.IFS_OrderSenderPending
TRUNCATE TABLE IMES3UAT.dbo.IFS_PackageTypeReceiverPending
TRUNCATE TABLE IMES3UAT.dbo.IFS_PackageTypeSenderPending
TRUNCATE TABLE IMES3UAT.dbo.IFS_ProductBarcodeReceiverPending
TRUNCATE TABLE IMES3UAT.dbo.IFS_ProductBarcodeSenderPending
TRUNCATE TABLE IMES3UAT.dbo.IFS_RackReceiverPending
TRUNCATE TABLE IMES3UAT.dbo.IFS_RackSenderPending
TRUNCATE TABLE IMES3UAT.dbo.LGS_BTOAutoOrderPPG1
TRUNCATE TABLE IMES3UAT.dbo.LGS_BTOAutoOrderPPG3
TRUNCATE TABLE IMES3UAT.dbo.LGS_BTODet
TRUNCATE TABLE IMES3UAT.dbo.LGS_BTOMstr
TRUNCATE TABLE IMES3UAT.dbo.LGS_CMZDet
TRUNCATE TABLE IMES3UAT.dbo.LGS_CMZMstr
TRUNCATE TABLE IMES3UAT.dbo.LGS_CMZOrderDet
TRUNCATE TABLE IMES3UAT.dbo.LGS_CMZOrderMstr
TRUNCATE TABLE IMES3UAT.dbo.LGS_DeliveryConfirm
TRUNCATE TABLE IMES3UAT.dbo.LGS_DeliveryDet
TRUNCATE TABLE IMES3UAT.dbo.LGS_DeliveryMstr
TRUNCATE TABLE IMES3UAT.dbo.LGS_DownBinRequest
TRUNCATE TABLE IMES3UAT.dbo.LGS_DownBinRequestDet
TRUNCATE TABLE IMES3UAT.dbo.LGS_HUPkgDet
TRUNCATE TABLE IMES3UAT.dbo.LGS_HUPkgLog
TRUNCATE TABLE IMES3UAT.dbo.LGS_HUPkgMstr
--TRUNCATE TABLE IMES3UAT.dbo.LGS_JISOrder
--TRUNCATE TABLE IMES3UAT.dbo.LGS_JISOrderDet
TRUNCATE TABLE IMES3UAT.dbo.LGS_JISScanLog
TRUNCATE TABLE IMES3UAT.dbo.LGS_JISScanSiteIndex
TRUNCATE TABLE IMES3UAT.dbo.LGS_PurchaseOrder
TRUNCATE TABLE IMES3UAT.dbo.LGS_PurchaseOrderHUBarcode
TRUNCATE TABLE IMES3UAT.dbo.LGS_PurchaseOrderProductBarcode
TRUNCATE TABLE IMES3UAT.dbo.LGS_PurchaseOrderRetrun
TRUNCATE TABLE IMES3UAT.dbo.lgs_purchaseplan
TRUNCATE TABLE IMES3UAT.dbo.LGS_ReceiptStatusInterface
TRUNCATE TABLE IMES3UAT.dbo.LGS_ShippingFreight
TRUNCATE TABLE IMES3UAT.dbo.LGS_SOReturnDet
TRUNCATE TABLE IMES3UAT.dbo.LGS_SOReturnMstr
TRUNCATE TABLE IMES3UAT.dbo.LGS_SpecialStkTransOrder
TRUNCATE TABLE IMES3UAT.dbo.LGS_SpecialStkTransOrderDet
TRUNCATE TABLE IMES3UAT.dbo.LGS_SRadjust
TRUNCATE TABLE IMES3UAT.dbo.LGS_UpBinRequest
TRUNCATE TABLE IMES3UAT.dbo.LGS_UpBinRequestDet
TRUNCATE TABLE IMES3UAT.dbo.LGS_WFMDirectPost
TRUNCATE TABLE IMES3UAT.dbo.LGS_WFMMaterialReqBarcode
TRUNCATE TABLE IMES3UAT.dbo.LGS_WFMMaterialReqBill
TRUNCATE TABLE IMES3UAT.dbo.LGS_WFMMaterialReqBillDet
TRUNCATE TABLE IMES3UAT.dbo.MFG_BarcodeBindDet
TRUNCATE TABLE IMES3UAT.dbo.MFG_BarcodeScanLog
TRUNCATE TABLE IMES3UAT.dbo.MFG_BOM_Disassembled
TRUNCATE TABLE IMES3UAT.dbo.MFG_ProduceSchedule
TRUNCATE TABLE IMES3UAT.dbo.MFG_ProduceScheduleDet
TRUNCATE TABLE IMES3UAT.dbo.MFG_ProductBarcode
TRUNCATE TABLE IMES3UAT.dbo.MFG_WorkOrder
TRUNCATE TABLE IMES3UAT.dbo.MFG_WorkOrderDeclare
TRUNCATE TABLE IMES3UAT.dbo.MFG_WorkOrderDet
TRUNCATE TABLE IMES3UAT.dbo.MFG_WorkOrderDetDeclare
TRUNCATE TABLE IMES3UAT.dbo.MFG_WorkOrderRoute
TRUNCATE TABLE IMES3UAT.dbo.MFG_WorkOrderRouteDeclare
TRUNCATE TABLE IMES3UAT.dbo.QCM_DefectLog
TRUNCATE TABLE IMES3UAT.dbo.QCM_DismantBarocdeLog
TRUNCATE TABLE IMES3UAT.dbo.QCM_QualityReviewPending
TRUNCATE TABLE IMES3UAT.dbo.QCM_UnqualifiedReview
TRUNCATE TABLE IMES3UAT.dbo.QCM_UnqualifiedReviewRev
TRUNCATE TABLE IMES3UAT.dbo.SYS_QADTransaction
TRUNCATE TABLE IMES3UAT.dbo.SYS_SAPTransaction
TRUNCATE TABLE IMES3UAT.dbo.SYS_SAPTransactionGather
TRUNCATE TABLE IMES3UAT.dbo.SYS_SerialNum
TRUNCATE TABLE IMES3UAT.dbo.SYS_UnhandleException
TRUNCATE TABLE IMES3UAT.dbo.WMS_BinReserve
TRUNCATE TABLE IMES3UAT.dbo.WMS_BinReserveDown
TRUNCATE TABLE IMES3UAT.dbo.WMS_COGI
TRUNCATE TABLE IMES3UAT.dbo.WMS_InTransit
TRUNCATE TABLE IMES3UAT.dbo.WMS_ProductBinChangeLog
TRUNCATE TABLE IMES3UAT.dbo.WMS_ProductBinDet
TRUNCATE TABLE IMES3UAT.dbo.WMS_SAPTransactionPending
TRUNCATE TABLE IMES3UAT.dbo.WMS_StkAlarm
TRUNCATE TABLE IMES3UAT.dbo.WMS_StkChangeHist
TRUNCATE TABLE IMES3UAT.dbo.WMS_StkChangePending
TRUNCATE TABLE IMES3UAT.dbo.WMS_StkDet
TRUNCATE TABLE IMES3UAT.dbo.WMS_StkOutDet
TRUNCATE TABLE IMES3UAT.dbo.WMS_StkOutMstr
TRUNCATE TABLE IMES3UAT.dbo.WMS_StkRctDet
TRUNCATE TABLE IMES3UAT.dbo.WMS_StkRctMstr
------切换的时候，需要清一下盘点的历史数据----------
--TRUNCATE TABLE IMES3UAT.dbo.WMS_StockTaking_HUPkgDet
--TRUNCATE TABLE IMES3UAT.dbo.WMS_StockTaking_HUPkgMstr
--TRUNCATE TABLE IMES3UAT.dbo.WMS_Stocktaking_Plan
--TRUNCATE TABLE IMES3UAT.dbo.WMS_Stocktaking_PlanDet
--TRUNCATE TABLE IMES3UAT.dbo.WMS_StockTaking_ProductBarcode
--TRUNCATE TABLE IMES3UAT.dbo.WMS_StockTaking_StkDet
--TRUNCATE TABLE IMES3UAT.dbo.WMS_StockTaking_StkDetTemp
TRUNCATE TABLE IMES3UAT.dbo.WMS_TODet
TRUNCATE TABLE IMES3UAT.dbo.WMS_TOMstr
TRUNCATE TABLE IMES3UAT.dbo.bar_mstr
TRUNCATE TABLE IMES3UAT.dbo.ct_mstr1
TRUNCATE TABLE IMES3UAT.dbo.ctd_det1
TRUNCATE TABLE IMES3UAT.dbo.hjd_det
TRUNCATE TABLE IMES3UAT.dbo.hjdts_det
TRUNCATE TABLE IMES3UAT.dbo.wxjtp_det

--常熟专用
TRUNCATE TABLE  dbo.MFG_ProdBarCodeCCRComps  --清条码关联的子件明细
DELETE FROM  dbo.LGS_PreAssembly  WHERE CreateTime <= '2016-11-17 00:00:00' --清预排序信息
DELETE FROM dbo.LGS_JISOrderDet WHERE SeqGuid IN ( SELECT Guid FROM dbo.LGS_JISOrder WHERE CreateTime <= '2016-11-17 00:00:00' ) --清排序单明细
DELETE FROM dbo.LGS_JISOrder WHERE CreateTime <= '2016-11-17 00:00:00' --清排序单
TRUNCATE TABLE dbo.LGS_JISPointInfo --清过点信息
TRUNCATE TABLE dbo.LGS_SvwM1Account --清导入的结算信息


--执行完成要跑一下存储过程P_MFG_DisassembleBOM
UPDATE dbo.WMS_StkMstr SET CheckNegStk = '1'  开启COGI
--修改SYS_User
--UPDATE SYS_User SET Password = 'nimda' WHERE UserAccount = 'admin'
--ISV如果当天下过采购单，要清空以下几张表
--SELECT * FROM LGS_PurchaseOrder WHERE orderno LIKE 'PYT16101000%'
--SELECT * FROM ORDER_HEADER WHERE QAD_ORDER_ID LIKE 'PYT16101000%'
--SELECT * FROM PURCHASE_ORDER WHERE ORDER_id in (SELECT order_id FROM ORDER_HEADER WHERE QAD_ORDER_ID LIKE 'PYT16101000%')
--SELECT * FROM PO_ITEM WHERE QAD_ORDER_ID LIKE 'PYT16101000%'









