ALTER TABLE dbo.SYS_SAPTransactionGather ADD RefGUID NVARCHAR(50) NULL 
ALTER TABLE dbo.SYS_SAPTransactionGather ADD Reserve1 NVARCHAR(50) NULL 
ALTER TABLE dbo.SYS_SAPTransactionGather ADD Reserve2 NVARCHAR(50) NULL 
ALTER TABLE dbo.SYS_SAPTransactionGather ADD Reserve3 NVARCHAR(50) NULL 

ALTER TABLE dbo.SYS_SAPTransaction ADD RefGUID NVARCHAR(50) NULL 
ALTER TABLE dbo.SYS_SAPTransaction ADD Reserve1 NVARCHAR(50) NULL 
ALTER TABLE dbo.SYS_SAPTransaction ADD Reserve2 NVARCHAR(50) NULL 
ALTER TABLE dbo.SYS_SAPTransaction ADD Reserve3 NVARCHAR(50) NULL 

ALTER TABLE dbo.WMS_StkRctMstr ADD RefGUID NVARCHAR(50) NULL 
ALTER TABLE dbo.WMS_StkOutMstr ADD RefGUID NVARCHAR(50) NULL 


