//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace I.MES.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    [MapWith(typeof(I.MES.Models.MFG_BarcodePrintLog))]
    public partial class MFG_BarcodePrintLog
    {
        public int ID { get; set; }
        public string Barcode { get; set; }
        public string Printer { get; set; }
        public string PrintMachine { get; set; }
        public Nullable<System.DateTime> PrintTime { get; set; }
        public string CreateUserAccount { get; set; }
        public string CreateMachine { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
