//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace I.MES.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    [MapWith(typeof(I.MES.Models.MFG_WorkSchedule))]
    public partial class MFG_WorkSchedule
    {
        public int ID { get; set; }
        public string FactoryCode { get; set; }
        public System.DateTime ProdDate { get; set; }
        public string PartNo { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string Unit { get; set; }
        public Nullable<int> IsDel { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string WorkVer { get; set; }
    }
}
