//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace I.MES.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    [MapWith(typeof(I.MES.Models.MFG_BarcodeBindDet))]
    public partial class MFG_BarcodeBindDet
    {
        public int ID { get; set; }
        public string BindType { get; set; }
        public string MainBarcode { get; set; }
        public string Barcode { get; set; }
        public string BindCfgName { get; set; }
        public Nullable<int> BindStatus { get; set; }
        public string BindUser { get; set; }
        public Nullable<System.DateTime> BindTime { get; set; }
        public string UnbindUser { get; set; }
        public Nullable<System.DateTime> UnbindTime { get; set; }
        public string BindScanSite { get; set; }
    }
}
