//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace I.MES.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    [MapWith(typeof(I.MES.Models.MFG_BarcodeScanLog))]
    public partial class MFG_BarcodeScanLog
    {
        public int ID { get; set; }
        public string FactoryCode { get; set; }
        public string ProdLineCode { get; set; }
        public string BarCode { get; set; }
        public string StationCode { get; set; }
        public string OrigPartNo { get; set; }
        public string OrigQualityStatus { get; set; }
        public string NewPartNo { get; set; }
        public string NewQualityStatus { get; set; }
        public string OpType { get; set; }
        public string OrderNo { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateMachine { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string ModifyMachine { get; set; }
    }
}
