//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace I.MES.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    [MapWith(typeof(I.MES.Models.MFG_ProductBarcode))]
    public partial class MFG_ProductBarcode
    {
        public long ID { get; set; }
        public string Barcode { get; set; }
        public string OrderNo { get; set; }
        public string CurrentPartNo { get; set; }
        public string QualityStatus { get; set; }
        public string ControlStatus { get; set; }
        public Nullable<System.DateTime> PrintTime { get; set; }
        public Nullable<int> BarcodeStatus { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateMachine { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string ModifyMachine { get; set; }
    }
}
