//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace I.MES.Library.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataEntities : DbContext
    {
        public DataEntities()
            : base("name=DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MFG_BarcodeBindDet> MFG_BarcodeBindDet { get; set; }
        public DbSet<MFG_BarcodeControlStatus> MFG_BarcodeControlStatus { get; set; }
        public DbSet<MFG_BarcodePrintLog> MFG_BarcodePrintLog { get; set; }
        public DbSet<MFG_BarcodeScanLog> MFG_BarcodeScanLog { get; set; }
        public DbSet<MFG_BOM> MFG_BOM { get; set; }
        public DbSet<MFG_BOM_Disassembled> MFG_BOM_Disassembled { get; set; }
        public DbSet<MFG_PartCategory> MFG_PartCategory { get; set; }
        public DbSet<MFG_PartDetail> MFG_PartDetail { get; set; }
        public DbSet<MFG_ProcRoute> MFG_ProcRoute { get; set; }
        public DbSet<MFG_ProdLine> MFG_ProdLine { get; set; }
        public DbSet<MFG_ProduceCategory> MFG_ProduceCategory { get; set; }
        public DbSet<MFG_ProduceLevel> MFG_ProduceLevel { get; set; }
        public DbSet<MFG_ProductBarcode> MFG_ProductBarcode { get; set; }
        public DbSet<MFG_ProductColor> MFG_ProductColor { get; set; }
        public DbSet<MFG_ProdWorkSetp> MFG_ProdWorkSetp { get; set; }
        public DbSet<MFG_ProdWorkStepParam> MFG_ProdWorkStepParam { get; set; }
        public DbSet<MFG_VehicleMode> MFG_VehicleMode { get; set; }
        public DbSet<MFG_WorkSchedule> MFG_WorkSchedule { get; set; }
        public DbSet<SYS_Company> SYS_Company { get; set; }
        public DbSet<SYS_Factory> SYS_Factory { get; set; }
        public DbSet<SYS_GlobalConfig> SYS_GlobalConfig { get; set; }
        public DbSet<SYS_GlobalDic> SYS_GlobalDic { get; set; }
        public DbSet<SYS_MachinePrinterPriv> SYS_MachinePrinterPriv { get; set; }
        public DbSet<SYS_Printer> SYS_Printer { get; set; }
        public DbSet<SYS_Prog> SYS_Prog { get; set; }
        public DbSet<SYS_ProgPriv> SYS_ProgPriv { get; set; }
        public DbSet<SYS_Role> SYS_Role { get; set; }
        public DbSet<SYS_RoleProgPriv> SYS_RoleProgPriv { get; set; }
        public DbSet<SYS_RPTMenu> SYS_RPTMenu { get; set; }
        public DbSet<SYS_SerialNum> SYS_SerialNum { get; set; }
        public DbSet<SYS_User> SYS_User { get; set; }
        public DbSet<SYS_UserRole> SYS_UserRole { get; set; }
        public DbSet<V_SYS_TABLE_STRUCT> V_SYS_TABLE_STRUCT { get; set; }
        public DbSet<SYS_UserFactoryPriv> SYS_UserFactoryPriv { get; set; }
        public DbSet<MFG_ProdStation> MFG_ProdStation { get; set; }
        public DbSet<MFG_RouteStation> MFG_RouteStation { get; set; }
        public DbSet<MFG_ScanPlugin> MFG_ScanPlugin { get; set; }
        public DbSet<MFG_ScanPluginParam> MFG_ScanPluginParam { get; set; }
        public DbSet<MFG_RoteConfig> MFG_RoteConfig { get; set; }
        public DbSet<MFG_Part> MFG_Part { get; set; }
        public DbSet<PP_BarCodeTrack> PP_BarCodeTrack { get; set; }
        public DbSet<PP_ThightRecord> PP_ThightRecord { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<V_MFG_SelectRoteConfig> V_MFG_SelectRoteConfig { get; set; }
        public DbSet<V_WorkStepParam> V_WorkStepParam { get; set; }
    }
}
