//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace I.MES.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    [MapWith(typeof(I.MES.Models.SYS_User))]
    public partial class SYS_User
    {
        public SYS_User()
        {
            this.SYS_UserRole = new HashSet<SYS_UserRole>();
        }
    
        public int ID { get; set; }
        public string UserAccount { get; set; }
        public string UserName { get; set; }
        public string UserWorkID { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> LatestLoginTime { get; set; }
        public string LatestLoginMachine { get; set; }
        public string LatestModifyUser { get; set; }
        public Nullable<System.DateTime> LatestModifyTime { get; set; }
        public string LatestModifyMachine { get; set; }
        public string CreateUserAccount { get; set; }
        public string CreateMachine { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string DomainAccount { get; set; }
    
        public virtual ICollection<SYS_UserRole> SYS_UserRole { get; set; }
    }
}
