//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace I.MES.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    [MapWith(typeof(I.MES.Models.SYS_Role))]
    public partial class SYS_Role
    {
        public SYS_Role()
        {
            this.SYS_RoleProgPriv = new HashSet<SYS_RoleProgPriv>();
            this.SYS_UserRole = new HashSet<SYS_UserRole>();
        }
    
        public int ID { get; set; }
        public string RoleCode { get; set; }
        public string RoleName { get; set; }
        public string RoleDesc { get; set; }
        public string CrtUser { get; set; }
        public string CrtTime { get; set; }
        public string CrtMachine { get; set; }
        public string LatestModifyUser { get; set; }
        public System.DateTime LatestModifyTime { get; set; }
        public string LatestModifyMachine { get; set; }
        public string CreateUserAccount { get; set; }
        public string CreateMachine { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string RoleID { get; set; }
    
        public virtual ICollection<SYS_RoleProgPriv> SYS_RoleProgPriv { get; set; }
        public virtual ICollection<SYS_UserRole> SYS_UserRole { get; set; }
    }
}
