//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace I.MES.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    [MapWith(typeof(I.MES.Models.V_SYS_TABLE_STRUCT))]
    public partial class V_SYS_TABLE_STRUCT
    {
        public string SchemaName { get; set; }
        public string TableName { get; set; }
        public string ColName { get; set; }
        public string TypeName { get; set; }
        public short Max_Length { get; set; }
        public bool IsPrimary { get; set; }
        public int IsIdentity { get; set; }
        public string defaultVaule { get; set; }
    }
}
