//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace I.MES.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    [MapWith(typeof(I.MES.Models.V_WorkStepParam))]
    public partial class V_WorkStepParam
    {
        public string StepID { get; set; }
        public string Default_image_address { get; set; }
        public string PartName { get; set; }
        public string Check_key { get; set; }
        public string Screw_the_number { get; set; }
        public string Screw_position { get; set; }
        public string torque { get; set; }
        public string torqueoffset { get; set; }
        public string Screw_picture_Pset { get; set; }
        public string Countdown_time { get; set; }
        public string printparam { get; set; }
        public string picparam { get; set; }
        public string checkparam { get; set; }
        public string inspectionparam { get; set; }
        public string presenceparam { get; set; }
    }
}
